config/routes.rb
Rails.application.routes.draw do
  resources :geolos
  
root "geolos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/geolo.rb
class Geolo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/geolos_controller.rb
class GeolosController < ApplicationController
  before_action :set_geolo, only: [:show, :edit, :update, :destroy]

  # GET /geolos
  # GET /geolos.json
  def index
    @geolos = Geolo.all
  end

  # GET /geolos/1
  # GET /geolos/1.json
  def show
  end

  # GET /geolos/new
  def new
    @geolo = Geolo.new
  end

  # GET /geolos/1/edit
  def edit
  end

  # POST /geolos
  # POST /geolos.json
  def create
    @geolo = Geolo.new(geolo_params)

    respond_to do |format|
      if @geolo.save
        format.html { redirect_to @geolo, notice: 'Geolo was successfully created.' }
        format.json { render :show, status: :created, location: @geolo }
      else
        format.html { render :new }
        format.json { render json: @geolo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /geolos/1
  # PATCH/PUT /geolos/1.json
  def update
    respond_to do |format|
      if @geolo.update(geolo_params)
        format.html { redirect_to @geolo, notice: 'Geolo was successfully updated.' }
        format.json { render :show, status: :ok, location: @geolo }
      else
        format.html { render :edit }
        format.json { render json: @geolo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /geolos/1
  # DELETE /geolos/1.json
  def destroy
    @geolo.destroy
    respond_to do |format|
      format.html { redirect_to geolos_url, notice: 'Geolo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_geolo
      @geolo = Geolo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def geolo_params
      params.require(:geolo).permit(:latitude, :longitude, :address, :description, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geolos_helper.rb
module GeolosHelper
end

app/views/geolos/_form.html.erb
<%= form_with(model: geolo, local: true) do |form| %>
  <% if geolo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(geolo.errors.count, "error") %> prohibited this geolo from being saved:</h2>

      <ul>
      <% geolo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :geolo_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :geolo_longitude %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :geolo_address %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :geolo_description %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :geolo_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/geolos/edit.html.erb
<h1>Editing Geolo</h1>

<%= render 'form', geolo: @geolo %>

<%= link_to 'Show', @geolo %> |
<%= link_to 'Back', geolos_path %>

app/views/geolos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Geolos</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>Description</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @geolos.each do |geolo| %>
      <tr>
        <td><%= geolo.latitude %></td>
        <td><%= geolo.longitude %></td>
        <td><%= geolo.address %></td>
        <td><%= geolo.description %></td>
        <td><%= geolo.title %></td>
        <td><%= link_to 'Show', geolo %></td>
        <td><%= link_to 'Edit', edit_geolo_path(geolo) %></td>
        <td><%= link_to 'Destroy', geolo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Geolo', new_geolo_path %>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 0,
      "lng": 0,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/geolos/new.html.erb
<h1>New Geolo</h1>

<%= render 'form', geolo: @geolo %>

<%= link_to 'Back', geolos_path %>

app/views/geolos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @geolo.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @geolo.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @geolo.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @geolo.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @geolo.title %>
</p>

<%= link_to 'Edit', edit_geolo_path(@geolo) %> |
<%= link_to 'Back', geolos_path %>

<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@geolo.latitude},#{@geolo.longitude}&markers=#{@geolo.latitude},#{@geolo.longitude}&zoom=7&size=640x400&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8", alt: "#{@geolo.title} on the map" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geolocalizacion</title>
    <%= csrf_meta_tags %>

    <script src="//maps.google.com/maps/api/js?key=[your API key]"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> 

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>